export const cities = [
  {
    slug: "berlin",
    name: "Berlin",
    title: "KI Agentur Berlin",
    region: "Berlin",
    description: "In der pulsierenden Startup-Metropole Berlin treffen Innovation und Technologie aufeinander. Als KI Agentur in Berlin helfen wir Unternehmen, Prozesse mit künstlicher Intelligenz zu automatisieren und im dynamischen Berliner Markt die Nase vorn zu behalten.",
    intro: "Berlin ist das digitale Herz Deutschlands – mit über 4.000 Startups und einer der aktivsten Tech-Szenen Europas. Unternehmen in Berlin stehen unter enormem Innovationsdruck. Wer hier nicht automatisiert, verliert gegenüber der Konkurrenz wertvolle Zeit und Ressourcen.",
    whyCity: "Berlin ist Deutschlands führender Startup-Hub und zieht internationale Talente und Investoren an. Der Berliner Markt ist schnelllebig: Unternehmen müssen schnell skalieren, effizient arbeiten und gleichzeitig Kosten senken. KI-Automatisierung ist dabei kein Luxus mehr – sondern Notwendigkeit.",
    industries: ["Tech-Startups & Scale-ups", "E-Commerce & Retail", "Medien & Kreativwirtschaft", "Fintech & Banking", "Tourismus & Gastronomie"],
    examples: [
      { title: "AI Chatbot für Berliner E-Commerce", desc: "Automatischer Kundensupport, der 80% der Anfragen ohne menschlichen Eingriff löst." },
      { title: "Marketing Automation für Startups", desc: "LinkedIn-Outreach und E-Mail-Sequenzen, die täglich neue Leads generieren." },
      { title: "KI Datenanalyse", desc: "Automatische Auswertung von Verkaufsdaten und Prognosen für bessere Entscheidungen." },
      { title: "Content AI für Agenturen", desc: "Automatische Erstellung von SEO-Texten, Social Posts und Newslettern." },
    ],
    keywords: "KI Agentur Berlin, AI Agentur Berlin, KI Beratung Berlin, KI Automatisierung Berlin, AI Lösungen Berlin, künstliche Intelligenz Berlin",
    metaTitle: "KI Agentur Berlin – KI Automatisierung & AI Lösungen | Jakub Kaczmarek",
    metaDesc: "KI Agentur Berlin: Prozessautomatisierung, AI Chatbots & Marketing Automation für Berliner Unternehmen. Kostenlose KI-Analyse anfordern.",
  },
  {
    slug: "hamburg",
    name: "Hamburg",
    region: "Hamburg",
    title: "KI Agentur Hamburg",
    description: "Als KI Agentur für Hamburg unterstützen wir Unternehmen in der Hansestadt dabei, durch Automatisierung und künstliche Intelligenz effizienter zu arbeiten – von der Logistik bis zum Handel.",
    intro: "Hamburg ist Deutschlands Tor zur Welt: Mit dem größten Hafen Europas, einer starken Handels- und Logistikbranche und einer wachsenden Digitalwirtschaft bietet Hamburg ideale Voraussetzungen für KI-Automatisierung.",
    whyCity: "Hamburger Unternehmen aus Handel, Logistik und Medien stehen vor komplexen Prozessen und internationalem Wettbewerb. KI-Lösungen helfen, Lieferketten zu optimieren, Kundenanfragen zu automatisieren und Marketing effizienter zu gestalten.",
    industries: ["Logistik & Shipping", "Handel & Import/Export", "Medien & Publishing", "Luftfahrt & Tourismus", "Finanzdienstleistungen"],
    examples: [
      { title: "Logistik-Automatisierung", desc: "KI-gestützte Routenplanung und automatische Dokumentenverarbeitung für Logistiker." },
      { title: "AI Customer Service für Händler", desc: "Mehrsprachiger Chatbot für internationale Kunden – 24/7 verfügbar." },
      { title: "Content Marketing Automation", desc: "Automatische Content-Erstellung für Hamburger Medienunternehmen." },
      { title: "KI-Leadgenerierung für B2B", desc: "Automatischer Outreach zu Zielunternehmen im DACH-Raum." },
    ],
    keywords: "KI Agentur Hamburg, AI Agentur Hamburg, KI Beratung Hamburg, KI Automatisierung Hamburg, AI Lösungen Hamburg, künstliche Intelligenz Hamburg",
    metaTitle: "KI Agentur Hamburg – KI Automatisierung & AI Lösungen | Jakub Kaczmarek",
    metaDesc: "KI Agentur Hamburg: Automatisierung für Logistik, Handel & Medien. AI Chatbots, Marketing Automation & KI Beratung. Jetzt kostenlos analysieren.",
  },
  {
    slug: "muenchen",
    name: "München",
    region: "Bayern",
    title: "KI Agentur München",
    description: "Als KI Agentur für München begleiten wir bayerische Unternehmen auf dem Weg in die KI-gestützte Zukunft. Von Mittelständlern bis zu Konzernen – wir automatisieren Prozesse und steigern die Effizienz.",
    intro: "München ist Deutschlands wirtschaftsstärkste Stadt und Heimat zahlreicher DAX-Konzerne, Hidden Champions und innovativer Startups. In der Isarmetropole trifft bayerische Tradition auf Hightech-Innovation.",
    whyCity: "Der Münchner Markt ist geprägt von hohen Lohnkosten und starkem Fachkräftemangel. KI-Automatisierung bietet Unternehmen die Möglichkeit, Prozesse zu skalieren, ohne proportional mehr Personal einzustellen.",
    industries: ["Automotive & Maschinenbau", "IT & Software", "Versicherungen & Finanzen", "Gesundheitswesen", "Immobilien & PropTech"],
    examples: [
      { title: "Prozessautomatisierung für KMU", desc: "Automatische Rechnungsverarbeitung, HR-Prozesse und Reportings." },
      { title: "AI Sales Automation", desc: "Automatisches CRM-Update, Lead-Scoring und Follow-up-Sequenzen." },
      { title: "KI-gestützte Marktanalyse", desc: "Echtzeit-Wettbewerbsanalyse und automatische Reports für Management." },
      { title: "Chatbot für Versicherungen", desc: "KI-Assistent, der Kunden bei Vertragsabschluss und Schadensmeldung unterstützt." },
    ],
    keywords: "KI Agentur München, AI Agentur München, KI Beratung München, KI Automatisierung München, AI Lösungen München, künstliche Intelligenz Bayern",
    metaTitle: "KI Agentur München – KI Automatisierung & AI Lösungen Bayern | Jakub Kaczmarek",
    metaDesc: "KI Agentur München: Automatisierung für Automotive, IT & Finanzen. AI Chatbots, KI Prozessautomatisierung & Beratung. Jetzt KI-Potenzial entdecken.",
  },
  {
    slug: "koeln",
    name: "Köln",
    region: "Nordrhein-Westfalen",
    title: "KI Agentur Köln",
    description: "Als KI Agentur für Köln helfen wir Unternehmen im Rheinland, durch KI-Automatisierung schneller zu wachsen, Kosten zu senken und Kundenerlebnisse zu verbessern.",
    intro: "Köln ist eines der wichtigsten Wirtschaftszentren Deutschlands: Mit einem starken Mediensektor, florierendem Handel und einer lebendigen Startup-Szene am Rhein bietet die Stadt hervorragende Möglichkeiten für KI-Innovation.",
    whyCity: "Kölner Unternehmen sind besonders in Medien, Handel und Kreativwirtschaft aktiv. KI-Automatisierung ermöglicht es, Content schneller zu produzieren, Kampagnen gezielter auszuspielen und Vertriebsprozesse effizienter zu gestalten.",
    industries: ["Medien & TV", "Kreativwirtschaft & Design", "Handel & Retail", "Versicherungen", "Beratung & Consulting"],
    examples: [
      { title: "Content Automation für Medienhäuser", desc: "KI-generierter Content, automatisches Tagging und SEO-Optimierung für Redaktionen." },
      { title: "AI Marketing für Retailer", desc: "Personalisierte Produktempfehlungen und automatisierte E-Mail-Kampagnen." },
      { title: "KI Recruiting-Automation", desc: "Automatisches Screening von Bewerbern und KI-gestütztes Matching." },
      { title: "Workflow Automation für Agenturen", desc: "Automatische Projektverwaltung, Reporting und Kundenkommunikation." },
    ],
    keywords: "KI Agentur Köln, AI Agentur Köln, KI Beratung Köln, KI Automatisierung Köln, AI Lösungen Köln, künstliche Intelligenz NRW",
    metaTitle: "KI Agentur Köln – KI Automatisierung & AI Lösungen NRW | Jakub Kaczmarek",
    metaDesc: "KI Agentur Köln: Automatisierung für Medien, Handel & Kreativwirtschaft. AI Lösungen, Chatbots & Marketing Automation. Kostenlos beraten lassen.",
  },
  {
    slug: "frankfurt",
    name: "Frankfurt",
    region: "Hessen",
    title: "KI Agentur Frankfurt",
    description: "Als KI Agentur für Frankfurt am Main unterstützen wir Finanz- und Wirtschaftsunternehmen dabei, durch KI-Automatisierung ihre Prozesse zu optimieren und Wettbewerbsvorteile zu sichern.",
    intro: "Frankfurt ist Europas Finanzzentrum – Heimat der EZB, zahlreicher Banken und internationaler Konzerne. In keiner anderen deutschen Stadt sind die Ansprüche an Effizienz, Compliance und Skalierbarkeit höher.",
    whyCity: "Frankfurter Unternehmen, insbesondere im Finanz- und Beratungssektor, profitieren enorm von KI-Automatisierung: Compliance-Checks, Dokumentenverarbeitung, Risikobewertung – alles lässt sich mit KI beschleunigen und skalieren.",
    industries: ["Banking & Finanzdienstleistungen", "Unternehmensberatung", "Immobilien", "Pharma & Life Sciences", "Logistik & Transport"],
    examples: [
      { title: "KI Compliance Automation", desc: "Automatische Prüfung von Verträgen und Dokumenten auf Compliance-Kriterien." },
      { title: "AI-gestütztes Reporting", desc: "Automatische Erstellung von Finanzberichten und Dashboards für Management." },
      { title: "Sales Automation für B2B", desc: "KI-gestützter Outreach zu Entscheidern in Banken und Konzernen." },
      { title: "KI Dokumentenverarbeitung", desc: "Automatisches Extrahieren und Verarbeiten von Daten aus PDFs und Formularen." },
    ],
    keywords: "KI Agentur Frankfurt, AI Agentur Frankfurt, KI Beratung Frankfurt, KI Automatisierung Frankfurt, AI Lösungen Frankfurt, künstliche Intelligenz Hessen",
    metaTitle: "KI Agentur Frankfurt – KI Automatisierung für Finance & Business | Jakub Kaczmarek",
    metaDesc: "KI Agentur Frankfurt: KI Automatisierung für Banken, Beratung & Konzerne. AI Lösungen, Prozessautomatisierung & KI Beratung. Jetzt anfragen.",
  },
  {
    slug: "stuttgart",
    name: "Stuttgart",
    region: "Baden-Württemberg",
    title: "KI Agentur Stuttgart",
    description: "Als KI Agentur für Stuttgart unterstützen wir Unternehmen in der Automobilregion und darüber hinaus dabei, mit KI-Automatisierung die Produktivität zu steigern und Abläufe zu modernisieren.",
    intro: "Stuttgart ist das Herz der deutschen Industrie: Hier sitzen Weltmarktführer wie Daimler, Bosch und Porsche. Die Region steht vor einem massiven Wandel – und KI ist der Schlüssel zur erfolgreichen Transformation.",
    whyCity: "Stuttgarter Unternehmen aus Industrie und Maschinenbau stehen vor dem Wandel durch Digitalisierung. KI-Automatisierung ermöglicht es, Fertigungsprozesse zu optimieren, Wartung vorherzusagen und Vertriebsprozesse zu modernisieren.",
    industries: ["Automotive & Zulieferer", "Maschinenbau", "Engineering & Consulting", "Handel & Handwerk", "Softwareunternehmen"],
    examples: [
      { title: "Predictive Maintenance mit KI", desc: "KI analysiert Maschinendaten und prognostiziert Ausfälle bevor sie passieren." },
      { title: "Vertriebsautomatisierung für B2B", desc: "Automatisches Lead-Nurturing und CRM-Pflege für Industrieunternehmen." },
      { title: "KI Dokumentenmanagement", desc: "Automatisches Sortieren und Indexieren von technischen Dokumenten und Zeichnungen." },
      { title: "AI Marketing für Handwerk", desc: "Automatisierte Kundenakquise und Bewertungsmanagement für lokale Betriebe." },
    ],
    keywords: "KI Agentur Stuttgart, AI Agentur Stuttgart, KI Beratung Stuttgart, KI Automatisierung Stuttgart, AI Lösungen Baden-Württemberg",
    metaTitle: "KI Agentur Stuttgart – KI Automatisierung für Industrie & Mittelstand | Jakub Kaczmarek",
    metaDesc: "KI Agentur Stuttgart: KI Lösungen für Automotive, Maschinenbau & Mittelstand. Prozessautomatisierung & AI Beratung. Kostenlose KI-Analyse.",
  },
  {
    slug: "duesseldorf",
    name: "Düsseldorf",
    region: "Nordrhein-Westfalen",
    title: "KI Agentur Düsseldorf",
    description: "Als KI Agentur für Düsseldorf helfen wir Unternehmen im Rheinland, mit maßgeschneiderten KI-Lösungen ihre Prozesse zu automatisieren und Wachstum zu skalieren.",
    intro: "Düsseldorf ist NRWs Wirtschaftskapitale: Internationale Konzerne, Modehäuser, Werbeagenturen und ein starker Mittelstand machen die Stadt zu einem idealen Markt für KI-Innovation.",
    whyCity: "Düsseldorf ist ein internationaler Business-Hub mit einem hohen Anteil an Unternehmensberatungen, Agenturen und Handelsunternehmen. KI-Automatisierung hilft diesen Unternehmen, schneller zu liefern und Kosten zu optimieren.",
    industries: ["Werbung & Marketing", "Mode & Lifestyle", "Unternehmensberatung", "Handel & Messen", "IT-Dienstleistungen"],
    examples: [
      { title: "Marketing Automation für Agenturen", desc: "Automatische Content-Erstellung, Social Scheduling und Performance-Reporting." },
      { title: "KI Kundenanalyse für Retail", desc: "Automatische Segmentierung und personalisierte Ansprache im E-Commerce." },
      { title: "AI Lead Generation für B2B", desc: "Intelligentes Prospecting und automatisierter Erstkontakt auf LinkedIn." },
      { title: "Chatbot für Messeunternehmen", desc: "KI-Assistent für Besucheranfragen, Terminbuchungen und Aussteller-Support." },
    ],
    keywords: "KI Agentur Düsseldorf, AI Agentur Düsseldorf, KI Beratung Düsseldorf, KI Automatisierung Düsseldorf, AI Lösungen NRW",
    metaTitle: "KI Agentur Düsseldorf – KI Automatisierung & AI Lösungen NRW | Jakub Kaczmarek",
    metaDesc: "KI Agentur Düsseldorf: Automatisierung für Marketing, Handel & Beratung. AI Chatbots & Marketing Automation. Jetzt kostenlose KI-Analyse sichern.",
  },
  {
    slug: "leipzig",
    name: "Leipzig",
    region: "Sachsen",
    title: "KI Agentur Leipzig",
    description: "Als KI Agentur für Leipzig unterstützen wir Unternehmen in Sachsen dabei, durch smarte KI-Automatisierung zu wachsen und digitale Prozesse aufzubauen.",
    intro: "Leipzig ist Ostdeutschlands aufstrebende Digitalmetropole: Mit einer jungen, kreativen Szene, wachsender Tech-Community und einem dynamischen Mittelstand bietet Leipzig ideale Bedingungen für KI-Innovation.",
    whyCity: "Leipziger Unternehmen profitieren von einem vergleichsweise günstigen Marktumfeld und einer wachsenden digitalen Infrastruktur. KI-Automatisierung bietet hier besonders großes Wachstumspotenzial.",
    industries: ["Kreativwirtschaft", "Handel & Logistik", "Gesundheitswesen", "Bildung & EdTech", "Startups & Gründer"],
    examples: [
      { title: "KI für Gründer & Startups", desc: "Automatisierte Marketing-Stacks, die mit kleinem Budget maximale Reichweite erzielen." },
      { title: "AI Content für Kreativagenturen", desc: "KI-gestützte Text- und Bilderstellung für Agenturen und Content Creator." },
      { title: "E-Commerce Automation", desc: "Produktbeschreibungen, Kundenmails und Retargeting automatisch generieren." },
      { title: "KI Prozessoptimierung für KMU", desc: "Automatische Rechnungslegung, Buchhaltungsvorbereitung und CRM-Pflege." },
    ],
    keywords: "KI Agentur Leipzig, AI Agentur Leipzig, KI Beratung Leipzig, KI Automatisierung Sachsen, AI Lösungen Leipzig",
    metaTitle: "KI Agentur Leipzig – KI Automatisierung & AI Lösungen Sachsen | Jakub Kaczmarek",
    metaDesc: "KI Agentur Leipzig: KI Automatisierung für Startups, KMU & Kreativwirtschaft in Sachsen. AI Lösungen & Beratung. Jetzt kostenlos informieren.",
  },
];

export function getCityBySlug(slug) {
  return cities.find(c => c.slug === slug) || null;
}